# Checking the dataset

In [1]:
import pandas as pd

reviews_df = pd.read_csv("restaurants_combined_reviews_final.csv")
final_df = pd.read_csv("restaurants_final_dataset_updated.csv")

print("Reviews dataset shape:", reviews_df.shape)
print("Final dataset shape:", final_df.shape)

Reviews dataset shape: (1173, 12)
Final dataset shape: (224, 17)

In [2]:
reviews_df

,place_id,restaurant_name,address,latitude,longitude,restaurant_rating,user_rating_count,review_text,review_rating,review_time,author_name,area
0,ChIJ5SO0EQ0Z6zkRTMnqUebrTqA,Drishya Lounge - Best Lounge in New Baneshwor,"Devkota Sadak, Kathmandu 44600, Nepal",27.692262,85.336472,4.5,1180.0,The food was delicious and tasty. staff was ve...,5.0,2025-10-24T10:00:20.000207376Z,Kabir Bhattrai,Baneshwor
1,ChIJ5SO0EQ0Z6zkRTMnqUebrTqA,Drishya Lounge - Best Lounge in New Baneshwor,"Devkota Sadak, Kathmandu 44600, Nepal",27.692262,85.336472,4.5,1180.0,Its honestly one of the prettiest spots I’ve b...,5.0,2025-08-09T06:42:53.288050672Z,Nirajan Neupane,Baneshwor
2,ChIJ5SO0EQ0Z6zkRTMnqUebrTqA,Drishya Lounge - Best Lounge in New Baneshwor,"Devkota Sadak, Kathmandu 44600, Nepal",27.692262,85.336472,4.5,1180.0,It was my first time visit @Drishya lounge and...,5.0,2025-05-22T10:26:00.123473Z,Kranti Dhakal,Baneshwor
3,ChIJ5SO0EQ0Z6zkRTMnqUebrTqA,Drishya Lounge - Best Lounge in New Baneshwor,"Devkota Sadak, Kathmandu 44600, Nepal",27.692262,85.336472,4.5,1180.0,I had the pleasure of dining at Drishya Lounge...,5.0,2025-03-07T17:43:42.037954Z,Avishek Rouniyar,Baneshwor
4,ChIJ5SO0EQ0Z6zkRTMnqUebrTqA,Drishya Lounge - Best Lounge in New Baneshwor,"Devkota Sadak, Kathmandu 44600, Nepal",27.692262,85.336472,4.5,1180.0,"I recently visited Drishya Lounge, and I must ...",5.0,2025-01-29T10:43:38.655406Z,Riya Subedi,Baneshwor
...,...,...,...,...,...,...,...,...,...,...,...,...
1168,ChIJQx0tsK8a6zkRVfsW8Wg0xBM,Sakotha Woh-Chatamari Fast Food,MCCH+PQH Chatubrahma MahaVihar (Tadhichen Baha...,27.671905,85.429407,4.6,24.0,This place serves only baara and potatoes. The...,5.0,2019-07-14T12:56:08.851456Z,dipesh raj manandhar,Bhaktapur Durbar Square
1169,ChIJQx0tsK8a6zkRVfsW8Wg0xBM,Sakotha Woh-Chatamari Fast Food,MCCH+PQH Chatubrahma MahaVihar (Tadhichen Baha...,27.671905,85.429407,4.6,24.0,Opens up around 1 or 2pm. Just bara (lentil pa...,5.0,2025-10-17T09:15:20.986774022Z,Sandeep Gyawali,Bhaktapur Durbar Square
1170,ChIJQx0tsK8a6zkRVfsW8Wg0xBM,Sakotha Woh-Chatamari Fast Food,MCCH+PQH Chatubrahma MahaVihar (Tadhichen Baha...,27.671905,85.429407,4.6,24.0,This place is famous for newari dish Baara and...,4.0,2022-06-19T15:43:11.661521Z,saru shrestha,Bhaktapur Durbar Square
1171,ChIJQx0tsK8a6zkRVfsW8Wg0xBM,Sakotha Woh-Chatamari Fast Food,MCCH+PQH Chatubrahma MahaVihar (Tadhichen Baha...,27.671905,85.429407,4.6,24.0,This place was awesome. Food was freshly made ...,5.0,2025-08-31T13:03:19.777128580Z,John Dellamore,Bhaktapur Durbar Square
1172,ChIJQx0tsK8a6zkRVfsW8Wg0xBM,Sakotha Woh-Chatamari Fast Food,MCCH+PQH Chatubrahma MahaVihar (Tadhichen Baha...,27.671905,85.429407,4.6,24.0,They have been serving mouth-watering traditio...,3.0,2022-02-08T13:58:26.642876Z,Sagun Raj Lage,Bhaktapur Durbar Square

In [3]:
final_df

,place_id,restaurant_name,address,latitude,longitude,restaurant_rating,user_rating_count,area,competitor_count_500m,nearest_competitor_distance,avg_competitor_rating_500m,avg_competitor_reviews_500m,distance_to_bus_stop,distance_to_school,distance_to_office,restaurant_type,price_level
0,ChIJ-RNxuIUZ6zkRsDFn-ciYwkQ,CityScape Garden Grill,"Rooftop of Computer Bazaar Next to StarMall, P...",27.706574,85.322985,3.4,272.0,New Road,0,532.737092,0.000000,0.000000,95.151209,230.270673,306.808472,restaurant,NaN
1,ChIJ09Q2F34Z6zkRLHrFvGWnMV8,Bardali Restro & Meetings,"Kathmandu 44600, Nepal",27.682750,85.332481,3.8,559.0,Baneshwor,0,567.328264,0.000000,0.000000,512.814556,270.671749,202.096460,family_restaurant,NaN
2,ChIJ0eBjuSgZ6zkRFrzS1BS9v-w,Nepalaya Rooftop Restaurant,"Thamel, Kwabahal-17, Inside Hotel Nepalaya, Ka...",27.711473,85.311557,4.7,997.0,New Road,19,78.904699,4.547368,917.631579,486.090841,438.139395,311.724242,restaurant,PRICE_LEVEL_MODERATE
3,ChIJ0xX1rSsZ6zkRuZtJOPFTpNE,Crunchy Corner Mid Baneshwo,"Miteri marga Kathmandu, काठमाडौँ 44600, Nepal",27.698303,85.338556,2.9,180.0,Baneshwor,18,4.614885,4.150000,506.555556,587.355671,92.284507,99.102546,restaurant,NaN
4,ChIJ11f3NxUZ6zkRux1Yb9Tgmbo,SUNDOWN by Karma KTM,"United World Trade Centre, Tripura Marg, Kathm...",27.693957,85.313799,4.2,1025.0,New Road,0,850.056236,0.000000,0.000000,77.328594,212.834129,85.952312,restaurant,PRICE_LEVEL_EXPENSIVE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
219,ChIJYTnknOsb6zkRxnFiQt4CFN8,Durbar Coffee & Eatery,"MCCG+WJP, Bhaktapur 44800, Nepal",27.672341,85.426608,4.6,26.0,Bhaktapur Durbar Square,36,74.280843,4.222857,831.428571,340.529417,82.291203,175.311421,coffee_shop,NaN
220,ChIJ-6p-wuYb6zkRi5d8PhptS0M,Durbar Thakali Grill,"M9GX+J7, Radhe Radhe Rd, Madhyapur Thimi, Nepal",27.676519,85.398204,3.5,384.0,Bhaktapur Durbar Square,2,185.305529,3.700000,193.500000,206.677261,370.561397,48.976964,korean_restaurant,PRICE_LEVEL_MODERATE
221,ChIJv_9Pr3Qb6zkRj3OehCnTFzk,Cafe Boh,"Radhe Radhe, Bhaktapur 44800, Nepal",27.678350,85.398411,4.5,278.0,Bhaktapur Durbar Square,2,203.853922,3.200000,246.500000,182.318492,258.563732,96.639986,restaurant,NaN
222,ChIJ7ysDSokb6zkRJgcO30l_m-w,HOTEL CENTRAL BHAKTAPUR,"Durbar square -2 Nearby Balakhu, Ganesh Temple...",27.672775,85.429650,4.7,43.0,Bhaktapur Durbar Square,35,21.330844,4.252941,819.382353,402.071475,95.063443,275.100133,hotel,NaN
223,ChIJQx0tsK8a6zkRVfsW8Wg0xBM,Sakotha Woh-Chatamari Fast Food,MCCH+PQH Chatubrahma MahaVihar (Tadhichen Baha...,27.671905,85.429407,4.6,24.0,Bhaktapur Durbar Square,34,4.038902,4.248485,843.636364,498.005373,178.784509,293.445635,fast_food_restaurant,NaN